spring:
# 1) ?? ?? ?? ??
config:
import: optional:classpath:properties/env.properties

application:
name: wannab-book-service
profiles:
active: green

server:
port: 10390   # Book Service green ????

eureka:
client:
register-with-eureka: true
fetch-registry: true
service-url:
defaultZone: http://${EUREKA_USERNAME}:${EUREKA_PASSWORD}@220.67.216.11:10380/eureka
instance:
hostname: book-service-green

---

# blue ???? ??? ?
spring:
config:
activate:
on-profile: blue

server:
port: 10391   # Book Service blue ????

eureka:
client:
service-url:
defaultZone: http://${EUREKA_USERNAME}:${EUREKA_PASSWORD}@220.67.216.11:10380/eureka
instance:
hostname: book-service-blue
