spring:
  application:
    name: book-service
  lifecycle:
    timeout-per-shutdown-phase: 30s
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    redis:
      host: 11.11.11.11
      port: 6666
      password: secret
      database: 333
  cloud:
    discovery:
      enabled: false
    config:
      enabled: false

dbcp2:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
    initial-size: 5
    max-total: 5
    max-idle: 5
    min-idle: 5
    between-eviction-millis: 300000
    min-evictable-idle-millis: 600000
    num-tests-per-eviction-run: 3

server:
  port: 10390
  shutdown: graceful

eureka:
  client:
    enabled: false

management:
  health:
    elasticsearch:
      enabled: false

aladin:
  api:
    base-url: "http://secret/"
    ttb-key: "secret"

elasticsearch:
  host: localhost
  port: 9200
  username: secret
  password: secret
  index:
    book: wannab_books_v1
