### 도서 등록 요청
POST http://localhost:8082/api/admin/books
Content-Type: application/json

{
  "title": "이펙티브 자바",
  "description": "자바를 더 잘 쓰기 위한 모범 사례 모음집",
  "publicationDate": "2024-05-01",
  "originPrice": 32000,
  "stock": 100,
  "bookChapter": "1장 객체 생성과 파괴",
  "isbn": "9788968481901",
  "status": true,
  "categories": ["프로그래밍", "자바"],
  "authors": ["조슈아 블로크"],
  "publishers": ["인사이트"]
}


### 도서 조회
GET http://localhost:8082/api/admin/books?page=0&size=10
Accept: application/json

### 도서 상세 조회
GET http://localhost:8082/api/books/1
Accept: application/json

### 도서 수정
PUT http://localhost:8082/api/admin/books/1
Content-Type: application/json
Accept: application/json

{
  "title": "리팩터링 2판",
  "description": "코드를 개선하는 객체지향 리팩터링 가이드",
  "publicationDate": "2023-06-10",
  "originPrice": 35000,
  "stock": 100,
  "bookChapter": "1. 리팩터링 개요\n2. 코드 스멜",
  "isbn": "9788966263061",
  "status": true,
  "categories": ["프로그래밍", "소프트웨어 공학"],
  "authors": ["마틴 파울러"],
  "publishers": ["한빛미디어"]
}

### 도서 삭제
DELETE http://localhost:8082/api/admin/books/2