### 도서 등록 요청
POST http://localhost:10390/api/admin/books
Content-Type: application/json

{
  "title": "이펙티브 자바",
  "description": "자바를 더 잘 쓰기 위한 모범 사례 모음집",
  "publicationDate": "2024-05-01",
  "originPrice": 32000,
  "stock": 100,
  "bookChapter": "1장 객체 생성과 파괴",
  "isbn": "9788968481901",
  "status": true,
  "categories": "프로그래밍,자바",
  "authors": "조슈아 블로크,한강",
  "publishers": "인사이트, 교보문고",
  "bookImages": "https://example.com/img1.jpg,https://example.com/img2.jpg"
}


### 도서 조회
GET http://localhost:10390/api/admin/books?page=0&size=10
Accept: application/json

### 도서 상세 조회
GET http://localhost:10390/api/books/1
Accept: application/json

### 도서 수정
PUT http://localhost:10390/api/admin/books/1
Content-Type: application/json
Accept: application/json

{
  "title": "리팩터링 2판",
  "description": "코드를 개선하는 객체지향 리팩터링 가이드",
  "publicationDate": "2023-06-10",
  "originPrice": 35000,
  "stock": 100,
  "bookChapter": "1. 리팩터링 개요\n2. 코드 스멜",
  "isbn": "9788966263061",
  "status": true,
  "categories": "프로그래밍,수정 자바",
  "authors": "조슈아 블로크,수정 한강",
  "publishers": "인사이트, 수정 교보문고",
  "bookImages": "https://example.com/img4.jpg,https://example.com/img5.jpg"

}

### 도서 삭제
DELETE http://localhost:10390/api/admin/books/2₩