### 도서 리뷰 등록
POST http://localhost:10390/api/reviews/books/1
Content-Type: application/json
X-USER-ID: 123

{
  "reviewContent": "이 책 정말 재밌어요!",
  "reviewScore": 4,
  "reviewCreatedAt": "2025-06-27T10:00:00",
  "obId": 1001
}



### 로그인한 회원 기준 리뷰 목록 조회
GET http://localhost:10390/api/reviews/me?page=0&size=10
X-USER-ID: 123



### 특정 도서 기준 리뷰 목록 조회
GET http://localhost:10390/api/reviews/books/1?page=0&size=10



### 리뷰 수정
PUT http://localhost:10390/api/reviews/1
Content-Type: application/json

{
  "reviewContent": "수정된 리뷰 내용입니다.",
  "reviewScore": 4,
  "reviewUpdatedAt": "2025-06-27T15:00:00"
}



### 리뷰 삭제
DELETE http://localhost:10390/api/reviews/1


### 도서 리뷰 평균 점수 조회
GET http://localhost:10390/api/reviews/books/1/average
