INSERT INTO category (id, name, parent_id) VALUES (1, '소설/시/희곡', NULL);
INSERT INTO category (id, name, parent_id) VALUES (2, '에세이', NULL);
INSERT INTO category (id, name, parent_id) VALUES (3, '경제경영', NULL);
INSERT INTO category (id, name, parent_id) VALUES (4, '자기계발', NULL);
INSERT INTO category (id, name, parent_id) VALUES (5, '인문학', NULL);
INSERT INTO category (id, name, parent_id) VALUES (6, '역사', NULL);
INSERT INTO category (id, name, parent_id) VALUES (7, '사회과학', NULL);
INSERT INTO category (id, name, parent_id) VALUES (8, '과학', NULL);
INSERT INTO category (id, name, parent_id) VALUES (9, '예술/대중문화', NULL);
INSERT INTO category (id, name, parent_id) VALUES (10, '종교/역학', NULL);
INSERT INTO category (id, name, parent_id) VALUES (11, '어린이', NULL);
INSERT INTO category (id, name, parent_id) VALUES (12, '유아', NULL);
INSERT INTO category (id, name, parent_id) VALUES (13, '좋은부모', NULL);
INSERT INTO category (id, name, parent_id) VALUES (14, '청소년', NULL);
INSERT INTO category (id, name, parent_id) VALUES (15, '요리/살림', NULL);
INSERT INTO category (id, name, parent_id) VALUES (16, '건강/취미', NULL);
INSERT INTO category (id, name, parent_id) VALUES (17, '여행', NULL);
INSERT INTO category (id, name, parent_id) VALUES (18, '외국어', NULL);
INSERT INTO category (id, name, parent_id) VALUES (19, '컴퓨터/모바일', NULL);
INSERT INTO category (id, name, parent_id) VALUES (20, '만화', NULL);
INSERT INTO category (id, name, parent_id) VALUES (21, '잡지', NULL);
INSERT INTO category (id, name, parent_id) VALUES (22, '수험서/자격증', NULL);
INSERT INTO category (id, name, parent_id) VALUES (23, '대학교재', NULL);
INSERT INTO category (id, name, parent_id) VALUES (24, '참고서', NULL);
INSERT INTO category (id, name, parent_id) VALUES (25, '전집/중고전집', NULL);
INSERT INTO category (id, name, parent_id) VALUES (26, '달력/기타', NULL);
INSERT INTO category (id, name, parent_id) VALUES (27, '한국소설', 1);
INSERT INTO category (id, name, parent_id) VALUES (28, '일본소설', 1);
INSERT INTO category (id, name, parent_id) VALUES (29, '중국소설', 1);
INSERT INTO category (id, name, parent_id) VALUES (30, '영미소설', 1);
INSERT INTO category (id, name, parent_id) VALUES (31, '유럽소설', 1);
INSERT INTO category (id, name, parent_id) VALUES (32, '기타 나라 소설', 1);
INSERT INTO category (id, name, parent_id) VALUES (33, '고전소설', 1);
INSERT INTO category (id, name, parent_id) VALUES (34, '장르소설', 1);
INSERT INTO category (id, name, parent_id) VALUES (35, '시', 1);
INSERT INTO category (id, name, parent_id) VALUES (36, '희곡', 1);
INSERT INTO category (id, name, parent_id) VALUES (37, '세계문학전집', 1);
INSERT INTO category (id, name, parent_id) VALUES (38, '한국에세이', 2);
INSERT INTO category (id, name, parent_id) VALUES (39, '외국에세이', 2);
INSERT INTO category (id, name, parent_id) VALUES (40, '인물/평전', 2);
INSERT INTO category (id, name, parent_id) VALUES (41, '명상/치유 에세이', 2);
INSERT INTO category (id, name, parent_id) VALUES (42, '경제학/경제일반', 3);
INSERT INTO category (id, name, parent_id) VALUES (43, '경영일반', 3);
INSERT INTO category (id, name, parent_id) VALUES (44, '마케팅/세일즈', 3);
INSERT INTO category (id, name, parent_id) VALUES (45, 'CEO/비즈니스맨', 3);
INSERT INTO category (id, name, parent_id) VALUES (46, '재테크/투자', 3);
INSERT INTO category (id, name, parent_id) VALUES (47, '성공학', 3);
INSERT INTO category (id, name, parent_id) VALUES (48, '주식/증권', 3);
INSERT INTO category (id, name, parent_id) VALUES (49, '기업 경영/리더십', 3);
INSERT INTO category (id, name, parent_id) VALUES (50, 'e-비즈니스', 3);
INSERT INTO category (id, name, parent_id) VALUES (51, '성공/처세', 4);
INSERT INTO category (id, name, parent_id) VALUES (52, '자기능력계발', 4);
INSERT INTO category (id, name, parent_id) VALUES (53, '인간관계', 4);
INSERT INTO category (id, name, parent_id) VALUES (54, '화술/협상', 4);
INSERT INTO category (id, name, parent_id) VALUES (55, '여성', 4);
INSERT INTO category (id, name, parent_id) VALUES (56, '비즈니스 능력', 4);
INSERT INTO category (id, name, parent_id) VALUES (57, '시간관리', 4);
INSERT INTO category (id, name, parent_id) VALUES (58, '인문학일반', 5);
INSERT INTO category (id, name, parent_id) VALUES (59, '심리학', 5);
INSERT INTO category (id, name, parent_id) VALUES (60, '교육학', 5);
INSERT INTO category (id, name, parent_id) VALUES (61, '철학', 5);
INSERT INTO category (id, name, parent_id) VALUES (62, '문학이론', 5);
INSERT INTO category (id, name, parent_id) VALUES (63, '언어학', 5);
INSERT INTO category (id, name, parent_id) VALUES (64, '독서/글쓰기', 5);
INSERT INTO category (id, name, parent_id) VALUES (65, '성과 문화', 5);
INSERT INTO category (id, name, parent_id) VALUES (66, '정치/사회 비평', 5);
INSERT INTO category (id, name, parent_id) VALUES (67, '역사일반', 6);
INSERT INTO category (id, name, parent_id) VALUES (68, '한국사', 6);
INSERT INTO category (id, name, parent_id) VALUES (69, '동양사', 6);
INSERT INTO category (id, name, parent_id) VALUES (70, '서양사', 6);
INSERT INTO category (id, name, parent_id) VALUES (71, '세계사', 6);
INSERT INTO category (id, name, parent_id) VALUES (72, '신화', 6);
INSERT INTO category (id, name, parent_id) VALUES (73, '역사인물', 6);
INSERT INTO category (id, name, parent_id) VALUES (74, '정치/사회', 7);
INSERT INTO category (id, name, parent_id) VALUES (75, '법학', 7);
INSERT INTO category (id, name, parent_id) VALUES (76, '언론/미디어', 7);
INSERT INTO category (id, name, parent_id) VALUES (77, '사회문제/복지', 7);
INSERT INTO category (id, name, parent_id) VALUES (78, '여성학/젠더', 7);
INSERT INTO category (id, name, parent_id) VALUES (79, '인권', 7);
INSERT INTO category (id, name, parent_id) VALUES (80, '기초과학', 8);
INSERT INTO category (id, name, parent_id) VALUES (81, '교양과학', 8);
INSERT INTO category (id, name, parent_id) VALUES (82, '의학', 8);
INSERT INTO category (id, name, parent_id) VALUES (83, '공학', 8);
INSERT INTO category (id, name, parent_id) VALUES (84, 'IT 모바일', 8);
INSERT INTO category (id, name, parent_id) VALUES (85, '생명과학', 8);
INSERT INTO category (id, name, parent_id) VALUES (86, '지구과학', 8);
INSERT INTO category (id, name, parent_id) VALUES (87, '예술일반', 9);
INSERT INTO category (id, name, parent_id) VALUES (88, '미술', 9);
INSERT INTO category (id, name, parent_id) VALUES (89, '음악', 9);
INSERT INTO category (id, name, parent_id) VALUES (90, '건축', 9);
INSERT INTO category (id, name, parent_id) VALUES (91, '사진', 9);
INSERT INTO category (id, name, parent_id) VALUES (92, '영화', 9);
INSERT INTO category (id, name, parent_id) VALUES (93, '연극/뮤지컬', 9);
INSERT INTO category (id, name, parent_id) VALUES (94, '디자인', 9);
INSERT INTO category (id, name, parent_id) VALUES (95, '만화/애니메이션', 9);
INSERT INTO category (id, name, parent_id) VALUES (96, '대중문화/비평', 9);
INSERT INTO category (id, name, parent_id) VALUES (97, '종교일반', 10);
INSERT INTO category (id, name, parent_id) VALUES (98, '기독교(개신교)', 10);
INSERT INTO category (id, name, parent_id) VALUES (99, '천주교(가톨릭)', 10);
INSERT INTO category (id, name, parent_id) VALUES (100, '불교', 10);
INSERT INTO category (id, name, parent_id) VALUES (101, '기타 종교', 10);
INSERT INTO category (id, name, parent_id) VALUES (102, '역학/사주', 10);
INSERT INTO category (id, name, parent_id) VALUES (103, '유아', 11);
INSERT INTO category (id, name, parent_id) VALUES (104, '어린이 문학', 11);
INSERT INTO category (id, name, parent_id) VALUES (105, '어린이 교양', 11);
INSERT INTO category (id, name, parent_id) VALUES (106, '어린이 학습', 11);
INSERT INTO category (id, name, parent_id) VALUES (107, '어린이 영어', 11);
INSERT INTO category (id, name, parent_id) VALUES (108, '초등 참고서', 11);
INSERT INTO category (id, name, parent_id) VALUES (109, '그림책', 103);
INSERT INTO category (id, name, parent_id) VALUES (110, '놀이책', 103);
INSERT INTO category (id, name, parent_id) VALUES (111, '학습/인지', 103);
INSERT INTO category (id, name, parent_id) VALUES (112, '생활/습관', 103);
INSERT INTO category (id, name, parent_id) VALUES (113, '0-3세', 103);
INSERT INTO category (id, name, parent_id) VALUES (114, '4-7세', 103);
INSERT INTO category (id, name, parent_id) VALUES (115, '자녀교육', 13);
INSERT INTO category (id, name, parent_id) VALUES (116, '임신/출산/육아', 13);
INSERT INTO category (id, name, parent_id) VALUES (117, '가족/부부', 13);
INSERT INTO category (id, name, parent_id) VALUES (118, '청소년 문학', 14);
INSERT INTO category (id, name, parent_id) VALUES (119, '청소년 교양', 14);
INSERT INTO category (id, name, parent_id) VALUES (120, '청소년 자기계발', 14);
INSERT INTO category (id, name, parent_id) VALUES (121, '청소년 학습법', 14);
INSERT INTO category (id, name, parent_id) VALUES (122, '요리일반', 15);
INSERT INTO category (id, name, parent_id) VALUES (123, '건강요리', 15);
INSERT INTO category (id, name, parent_id) VALUES (124, '생활요리', 15);
INSERT INTO category (id, name, parent_id) VALUES (125, '와인/커피/음료', 15);
INSERT INTO category (id, name, parent_id) VALUES (126, '인테리어/DIY', 15);
INSERT INTO category (id, name, parent_id) VALUES (127, '건강일반', 16);
INSERT INTO category (id, name, parent_id) VALUES (128, '스포츠/레저', 16);
INSERT INTO category (id, name, parent_id) VALUES (129, '뷰티/패션', 16);
INSERT INTO category (id, name, parent_id) VALUES (130, '취미/실용', 16);
INSERT INTO category (id, name, parent_id) VALUES (131, '게임', 16);
INSERT INTO category (id, name, parent_id) VALUES (132, '반려동물', 16);
INSERT INTO category (id, name, parent_id) VALUES (133, '국내여행', 17);
INSERT INTO category (id, name, parent_id) VALUES (134, '해외여행', 17);
INSERT INTO category (id, name, parent_id) VALUES (135, '테마여행', 17);
INSERT INTO category (id, name, parent_id) VALUES (136, '영어', 18);
INSERT INTO category (id, name, parent_id) VALUES (137, '일본어', 18);
INSERT INTO category (id, name, parent_id) VALUES (138, '중국어', 18);
INSERT INTO category (id, name, parent_id) VALUES (139, '기타 외국어', 18);
INSERT INTO category (id, name, parent_id) VALUES (140, '어학시험', 18);
INSERT INTO category (id, name, parent_id) VALUES (141, '컴퓨터일반', 19);
INSERT INTO category (id, name, parent_id) VALUES (142, 'OS', 19);
INSERT INTO category (id, name, parent_id) VALUES (143, '프로그래밍', 19);
INSERT INTO category (id, name, parent_id) VALUES (144, '네트워크/보안', 19);
INSERT INTO category (id, name, parent_id) VALUES (145, '데이터베이스', 19);
INSERT INTO category (id, name, parent_id) VALUES (146, '웹/모바일', 19);
INSERT INTO category (id, name, parent_id) VALUES (147, '게임', 19);
INSERT INTO category (id, name, parent_id) VALUES (148, '자격증', 19);
INSERT INTO category (id, name, parent_id) VALUES (149, '교양만화', 20);
INSERT INTO category (id, name, parent_id) VALUES (150, '순정만화', 20);
INSERT INTO category (id, name, parent_id) VALUES (151, '명랑/코믹', 20);
INSERT INTO category (id, name, parent_id) VALUES (152, 'SF/판타지', 20);
INSERT INTO category (id, name, parent_id) VALUES (153, '공포/추리', 20);
INSERT INTO category (id, name, parent_id) VALUES (154, '액션/무협', 20);
INSERT INTO category (id, name, parent_id) VALUES (155, '성인만화', 20);
INSERT INTO category (id, name, parent_id) VALUES (156, 'BL/GL', 20);
INSERT INTO category (id, name, parent_id) VALUES (157, '주간/월간지', 21);
INSERT INTO category (id, name, parent_id) VALUES (158, '계간/연간', 21);
INSERT INTO category (id, name, parent_id) VALUES (159, '해외잡지', 21);
INSERT INTO category (id, name, parent_id) VALUES (160, '공무원', 22);
INSERT INTO category (id, name, parent_id) VALUES (161, '자격증', 22);
INSERT INTO category (id, name, parent_id) VALUES (162, '국가고시', 22);
INSERT INTO category (id, name, parent_id) VALUES (163, '취업/상식', 22);
INSERT INTO category (id, name, parent_id) VALUES (164, '운전면허', 22);
INSERT INTO category (id, name, parent_id) VALUES (165, '전공도서', 23);
INSERT INTO category (id, name, parent_id) VALUES (166, '교양도서', 23);
INSERT INTO category (id, name, parent_id) VALUES (167, '초등참고서', 24);
INSERT INTO category (id, name, parent_id) VALUES (168, '중등참고서', 24);
INSERT INTO category (id, name, parent_id) VALUES (169, '고등참고서', 24);
INSERT INTO category (id, name, parent_id) VALUES (170, '유아/어린이', 25);
INSERT INTO category (id, name, parent_id) VALUES (171, '청소년/성인', 25);
INSERT INTO category (id, name, parent_id) VALUES (172, '달력/다이어리', 26);
INSERT INTO category (id, name, parent_id) VALUES (173, '가계부/용돈기입장', 26);
