name: PR Test and SonarQube Analysis

on:
  pull_request:
    branches:
      - develop
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Run test and SonarQube analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          if [ -f src/main/resources/application-ci.yml ]; then
            mvn clean verify \
              -Dspring.config.import=optional:classpath:/application-ci.yml \
              -Dspring.profiles.active=ci \
              org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
              -Dsonar.projectKey=wannab-book-service \
              -Dsonar.projectName='wannab-book-service' \
              -Dsonar.host.url=${SONAR_HOST_URL} \
              -Dsonar.login=${SONAR_TOKEN} \
              -Dsonar.pullrequest.key=${{ github.event.pull_request.number }} \
              -Dsonar.pullrequest.branch=${{ github.head_ref }} \
              -Dsonar.pullrequest.base=${{ github.base_ref }}
          fi

  test-success:
    needs: test
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - name: Test Notify Success
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{
                 "botName": "wannab bot",
                 "text": "✅ 테스트 성공!",
                 "attachments": [
                   {
                      "title" : "${{ github.repository }} 테스트 성공",
                      "text" : "👤 머지한 사람: ${{ github.actor }}\n브랜치: ${{ github.base_ref }}",
                      "color" : "green"
                   }
                 ]
               }' \
               "${{ secrets.DOORAY_WEBHOOK_URL }}"

  test-failure:
    needs: test
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
      - name: Test Notify Failure
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{
                 "botName": "wannab bot",
                 "text": "❌ 테스트 실패...",
                 "attachments": [
                   {
                      "title" : "${{ github.repository }} 테스트 실패",
                      "text" : "👤 머지한 사람: ${{ github.actor }}\n브랜치: ${{ github.base_ref }}",
                      "color" : "red"
                   }
                 ]
               }' \
               "${{ secrets.DOORAY_WEBHOOK_URL }}"

